# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06fb02023c34c9a87c4033c9481a92e9ab28461f4402c1143c3ba299f455d93e80c89f3c277e8764731ac6d7f8313a5e476724d80dccb9d7d5ee6abdb620411b

test:
  secret_key_base: 99a9049f4309e42aec66151d9b497ef91a387ae84f6cf484907aeb83cd0295e32fc8273a936ea8939932a5037a6af84e98c36060307380cac2f9c42fba8d5737

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
